'use client';
import {useCallback,useEffect,useState} from 'react';import {Aperture,ArrowUpRight,Plus,Upload,Heart,Download,RefreshCw,Image as ImageIcon,Check,Trash2} from 'lucide-react';import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';import {Checkbox} from '@/components/ui/checkbox';import {Progress} from '@/components/ui/progress';import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';import './dashboard.css';
type R=Record<string,any>;const money=(n:number,c='cad')=>new Intl.NumberFormat('en-CA',{style:'currency',currency:c.toUpperCase()}).format(n/100);
function Vacant({title,children}:{title:string,children:React.ReactNode}){return <Empty className="dash-empty"><EmptyHeader><Aperture/><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{children}</EmptyDescription></EmptyHeader></Empty>}
function Field({label,name,value,type='text',required=false}:{label:string,name:string,value?:any,type?:string,required?:boolean}){return <label className="dash-field">{label}<input name={name} defaultValue={value} type={type} required={required} step={type==='number'?'0.01':undefined}/></label>}
function Choice({label,value,change,options}:{label:string,value:string,change:(v:string)=>void,options:{value:string,label:string}[]}){return <label className="dash-field">{label}<Select value={value} onValueChange={change}><SelectTrigger><SelectValue placeholder="Choose one"/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></label>}
export default function Dashboard({owner}:{owner:boolean}){const[data,setData]=useState<R|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState(owner?'overview':'projects'),[modal,setModal]=useState(''),[editing,setEditing]=useState<R|null>(null),[projectId,setProjectId]=useState(''),[clientId,setClientId]=useState(''),[service,setService]=useState('Photography'),[stage,setStage]=useState('planning'),[currency,setCurrency]=useState('cad'),[published,setPublished]=useState(false),[download,setDownload]=useState(false),[busy,setBusy]=useState(false),[progress,setProgress]=useState<number|null>(null),[failed,setFailed]=useState<File[]>([]),[lightbox,setLightbox]=useState<R|null>(null),[items,setItems]=useState([{description:'',quantity:'1',amount:''}]),[deleting,setDeleting]=useState<{kind:string,id:string,label:string}|null>(null),[deleteText,setDeleteText]=useState('');
const refresh=useCallback(async()=>{try{const r=await fetch('/api/studio'),j:any=await r.json();if(!r.ok)throw new Error(j.error);setData(j);setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load the studio.')}},[]);useEffect(()=>{refresh();window.addEventListener('focus',refresh);return()=>window.removeEventListener('focus',refresh)},[refresh]);
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();Promise.resolve(context.registerTool({name:'open_studio_section',description:'Open a visible section of the studio workspace. Does not create or send data.',inputSchema:{type:'object',properties:{section:{type:'string',enum:owner?['overview','enquiries','clients','projects','invoices','documents','messages','settings']:['projects','invoices','documents','messages']}},required:['section'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{const valid=owner?['overview','enquiries','clients','projects','invoices','documents','messages','settings']:['projects','invoices','documents','messages'];if(!input||!valid.includes(input.section))throw new Error('Unknown section');setTab(input.section);return{section:input.section}}},{signal:life.signal})).catch(()=>{});return()=>life.abort()},[owner]);
async function action(payload:R){const r=await fetch('/api/studio',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),j:any=await r.json();if(!r.ok)throw new Error(j.error);await refresh();return j}
function askDelete(kind:string,id:string,label:string){setModal('');setDeleting({kind,id,label});setDeleteText('');setNotice('')}
async function confirmDelete(){if(!deleting||deleteText!=='DELETE')return;setBusy(true);try{await action({action:'delete',...deleting,confirm:deleteText});setDeleting(null);setModal('');setLightbox(null);setNotice('Deleted.')}catch(e){setNotice(e instanceof Error?e.message:'Unable to delete.')}finally{setBusy(false)}}
async function perform(payload:R){setBusy(true);try{await action(payload);setNotice('Saved.')}catch(e){setNotice(e instanceof Error?e.message:'Unable to save.')}finally{setBusy(false)}}
function open(kind:string,item:R|null=null){setEditing(item);setClientId(item?.client_id||data?.clients?.[0]?.id||'');setProjectId(item?.project_id||data?.projects?.[0]?.id||'');setService(item?.service||'Photography');setStage(item?.status||'planning');setPublished(!!item?.published);setDownload(!!item?.download_allowed);setItems([{description:'',quantity:'1',amount:''}]);setModal(kind);setNotice('')}
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setNotice('');const f=Object.fromEntries(new FormData(e.currentTarget));let p:R={...f,action:modal};if(modal==='project')p={...p,id:editing?.id,clientId,service,status:stage,published,downloadAllowed:download};if(['invoice','signature','message'].includes(modal))p.projectId=projectId;if(modal==='invoice')p={...p,currency,items:items.map(i=>({...i,quantity:Number(i.quantity),amount:Math.round(Number(i.amount)*100)})),taxBps:Math.round(Number(f.tax||0)*100),deposit:Math.round(Number(f.deposit||0)*100)};if(modal==='email')p.clientId=clientId;try{await action(p);setModal('');setNotice(modal==='email'?'Email sent.':modal==='signature'?'Signature request sent.':'Saved.')}catch(e){setNotice(e instanceof Error?e.message:'Unable to save.')}finally{setBusy(false)}}
async function upload(files:File[]){
  if(!projectId||!files.length)return;
  setBusy(true);setProgress(0);setNotice('');const errors:File[]=[];
  const request=async(payload:R)=>{const r=await fetch('/api/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Upload failed.');return j};
  try{for(let i=0;i<files.length;i++){
    const file=files[i];
    try{
      const prepared=await request({action:'prepare',projectId,name:file.name,type:file.type,size:file.size});
      await new Promise<void>((resolve,reject)=>{
        const x=new XMLHttpRequest();x.open('PUT',prepared.signedUrl);x.timeout=180000;
        x.upload.onprogress=e=>{if(e.lengthComputable)setProgress((i+e.loaded/e.total)/files.length*100)};
        x.onload=()=>x.status>=200&&x.status<300?resolve():reject(new Error('Storage upload failed. Retry the file.'));
        x.onerror=()=>reject(new Error('Connection interrupted.'));x.ontimeout=()=>reject(new Error('Upload timed out.'));
        const form=new FormData();form.append('cacheControl','0');form.append('',file);x.send(form);
      });
      await request({action:'complete',id:prepared.id});
    }catch(e){errors.push(file);setNotice(e instanceof Error?e.message:'Upload failed.')}
  }
  setFailed(errors);await refresh();if(!errors.length){setModal('gallery');setNotice(`${files.length} files added.`)}
  }finally{setProgress(null);setBusy(false)}
}
async function pay(i:R,deposit=false){setBusy(true);try{const r=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:i.id,deposit})}),j:any=await r.json();if(!r.ok)throw new Error(j.error);location.assign(j.url)}catch(e){setNotice(e instanceof Error?e.message:'Payment is unavailable.');setBusy(false)}}
const projects=data?.projects||[],selected=projects.find((p:R)=>p.id===projectId),media=(data?.media||[]).filter((m:R)=>m.project_id===projectId),isOwner=owner&&data?.owner,tabs=owner?['overview','enquiries','clients','projects','invoices','documents','messages','settings']:['projects','invoices','documents','messages'];const choice=(list:string[])=>list.map(s=>({value:s,label:s}));const projOptions=projects.map((p:R)=>({value:p.id,label:p.title}));function gallery(p:R){setProjectId(p.id);setModal('gallery');setNotice('')}
return <div className="dashboard"><header className="dash-header"><a className="logo" href="/"><img className="brand-mark" src="/ss-studio-logo.png" alt="" width="44" height="44"/><span>SUPER SNAP<small>STUDIO</small></span></a><div><span>{owner?'Studio workspace':'Your private space'}</span><a href="/">View website ↗</a><button onClick={async()=>{try{const r=await fetch('/api/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!r.ok)throw new Error('Unable to sign out. Please retry.');window.location.assign('/login')}catch(e){setNotice(e instanceof Error?e.message:'Unable to sign out.')}}}>Sign out</button></div></header><main className="dash-main"><div className="dash-title"><div><span className="eyebrow">{owner?'BEHIND THE FRAME':'MADE FOR YOU'}</span><h1>{owner?'Your studio, in focus.':'Your moments. All here.'}</h1><p>{data?.user.email||'Loading your workspace…'}</p></div><button className="dash-button secondary" onClick={refresh}><RefreshCw size={16}/>Refresh</button></div>{error&&<div className="dash-notice" role="alert">{error}<button onClick={refresh}>Try again</button></div>}{notice&&<p className="dash-notice" role="status">{notice}</p>}{data&&<Tabs value={tab} onValueChange={setTab}><div className="dash-tabs-scroll"><TabsList variant="line" className="dash-tabs">{tabs.map(t=><TabsTrigger value={t} key={t}>{t==='projects'&&!owner?'My galleries':t[0].toUpperCase()+t.slice(1)}</TabsTrigger>)}</TabsList></div>
<TabsContent value="overview"><div className="dash-stats">{[[data.enquiries.filter((e:R)=>e.status==='new').length,'New enquiries'],[data.clients.length,'Clients'],[projects.length,'Projects']].map(([n,label])=><div className="stat" key={label}><strong>{n}</strong><span>{label}</span></div>)}</div><div className="dash-section-header"><h2>Ready for the next story</h2><button className="dash-button" onClick={()=>open('project')}><Plus size={16}/>New project</button></div><div className="overview-grid"><div className="dash-panel"><h3>A place for every frame</h3><p>Create a client, assign a project, and add photographs as they’re ready. Galleries stay private until you choose to publish them.</p><button className="dash-button secondary" onClick={()=>setTab('clients')}>Manage clients ↗</button></div><div className="dash-panel"><h3>Studio connections</h3>{Object.entries(data.integrations).map(([k,v])=><div className="connection-row" key={k}><span>{({payments:'Payments · Square',email:'Outgoing email · Resend',inbound:'Incoming email · Resend',signatures:'Signatures · DocuSeal'} as R)[k]}</span><span className="tag">{v?'Configured':'Awaiting setup'}</span></div>)}</div></div></TabsContent>
<TabsContent value="enquiries"><div className="dash-section-header"><h2>Session requests</h2><span>{data.enquiries.length} requests</span></div>{data.enquiries.length?data.enquiries.map((e:R)=><article className="dash-panel" key={e.id}><div className="request-heading"><div><span className="eyebrow">{e.service} · {new Date(e.created_at).toLocaleDateString()}</span><h3>{e.name}</h3></div><Choice label="Status" value={e.status} change={status=>perform({action:'enquiry',id:e.id,status})} options={choice(['new','contacted','booked','closed'])}/></div><p className="message-body">{e.details}</p><div className="request-meta"><a href={'mailto:'+e.email}>{e.email}</a>{e.phone&&<a href={'tel:'+e.phone}>{e.phone}</a>}<span>Preferred: {e.date||'Flexible'} {e.location}</span>{isOwner&&<button className="delete-action" onClick={()=>askDelete('enquiry',e.id,e.name+' enquiry')}><Trash2 size={14}/>Delete enquiry</button>}</div></article>):<Vacant title="The next story starts here">Requests from your website will appear here.</Vacant>}</TabsContent>
<TabsContent value="clients"><div className="dash-section-header"><h2>Your people</h2><button className="dash-button" onClick={()=>open('client')}><Plus size={16}/>Add client</button></div>{data.clients.length?<Table><TableHeader><TableRow><TableHead>Name</TableHead><TableHead>Email</TableHead><TableHead>Access</TableHead><TableHead>Contact</TableHead></TableRow></TableHeader><TableBody>{data.clients.map((c:R)=><TableRow key={c.id}><TableCell>{c.name}</TableCell><TableCell>{c.email}</TableCell><TableCell><span className="tag">{c.user_id?'Account linked':'Ready to sign in'}</span></TableCell><TableCell><div className="row-actions"><button onClick={()=>{open('email');setClientId(c.id)}}>Email ↗</button><button className="delete-action" onClick={()=>askDelete('client',c.id,c.name)}><Trash2 size={14}/>Delete</button></div></TableCell></TableRow>)}</TableBody></Table>:<Vacant title="Make room for your first client">Add their name and email, then create a project.</Vacant>}</TabsContent>
<TabsContent value="projects"><div className="dash-section-header"><h2>{owner?'Projects & galleries':'Your galleries'}</h2>{isOwner&&<button className="dash-button" onClick={()=>open('project')}><Plus size={16}/>New project</button>}</div>{projects.length?<div className="project-cards">{projects.map((p:R)=>{const cover=data.media.find((m:R)=>m.id===p.cover_id)||data.media.find((m:R)=>m.project_id===p.id&&m.type.startsWith('image/'));return <article className="project-card" key={p.id}><button className="project-thumb" onClick={()=>gallery(p)} aria-label={'Open '+p.title}>{cover?<img src={'/api/media/'+cover.id} alt={p.title}/>:<ImageIcon size={40}/>}<span>{p.media_count} frames</span></button><div className="project-card-body"><span className="eyebrow">{p.service} · {p.status}</span><h3><button onClick={()=>gallery(p)}>{p.title}</button></h3><p>{owner?p.client_name:'Your private gallery'}{p.date?' · '+p.date:''}</p><div className="project-actions"><button onClick={()=>gallery(p)}>Open gallery ↗</button>{isOwner&&<><button onClick={()=>open('project',p)}>Edit project</button><button className="delete-action" onClick={()=>askDelete('project',p.id,p.title)}><Trash2 size={14}/>Delete</button></>}</div>{isOwner&&<div className="project-tags"><span className="tag">{p.published?'Public portfolio':'Private'}</span>{p.selections_submitted===1&&<span className="tag">Selections received</span>}</div>}</div></article>})}</div>:<Vacant title={owner?'Your first project starts here':'Your gallery is on its way'}>{owner?'Add a client and create a project to start uploading.':'The studio will assign your gallery to the email you used to sign in. Contact us if you are expecting a delivery.'}</Vacant>}</TabsContent>
<TabsContent value="invoices"><div className="dash-section-header"><h2>Invoices & payments</h2>{isOwner&&<button className="dash-button" onClick={()=>open('invoice')}><Plus size={16}/>Create invoice</button>}</div>{!data.integrations.payments&&<p className="setup-note">Square payments are awaiting connection. No payment is recorded without provider confirmation.</p>}{data.invoices.length?data.invoices.map((i:R)=><article className="dash-panel invoice-card" key={i.id}><div><span className="eyebrow">{i.number}</span><h3>{money(i.total,i.currency)}</h3><p>{owner?<>Client: {i.client_name||'Unknown'}<br/>Project: {projects.find((p:R)=>p.id===i.project_id)?.title||'Unknown'}</>:i.currency.toUpperCase()}</p><span className="tag">{i.paid>=i.total?'Paid':i.refunded?'Refunded / balance due':i.paid>0?'Partially paid':i.due&&i.due<new Date().toISOString().slice(0,10)?'Overdue':'Awaiting payment'}</span></div><div><p>Paid: {money(i.paid,i.currency)}<br/>Remaining: {money(Math.max(0,i.total-i.paid),i.currency)}<br/>Due: {i.due||'To be agreed'}</p><div className="button-row"><a className="dash-button secondary" href={'/api/invoices/'+i.id}><Download size={16}/>PDF</a>{!owner&&i.paid<i.total&&<><button className="dash-button" disabled={busy||!data.integrations.payments} onClick={()=>pay(i)}>Pay balance with Square</button>{i.deposit>i.paid&&<button className="dash-button secondary" disabled={busy||!data.integrations.payments} onClick={()=>pay(i,true)}>Pay deposit with Square</button>}</>}{isOwner&&<button className="delete-action" onClick={()=>askDelete('invoice',i.id,i.number)}><Trash2 size={14}/>Delete invoice</button>}</div></div></article>):<Vacant title="No invoices yet">Invoices and verified payment balances will appear here.</Vacant>}</TabsContent>
<TabsContent value="documents"><div className="dash-section-header"><h2>Documents & signatures</h2>{isOwner&&<button className="dash-button" disabled={!data.integrations.signatures} onClick={()=>open('signature')}>Request signature</button>}</div>{!data.integrations.signatures&&<p className="setup-note">Document signing is awaiting a DocuSeal connection. Signed status will come from verified provider updates.</p>}{data.documents.length?data.documents.map((d:R)=><article key={d.id} className="dash-panel document-row"><div><h3>{d.title}</h3><span className="tag">{d.status}</span></div>{d.status==='completed'?<div>{d.completed_url&&<a href={d.completed_url} target="_blank" rel="noreferrer">Signed PDF ↗</a>}{d.audit_url&&<a href={d.audit_url} target="_blank" rel="noreferrer">Audit record ↗</a>}</div>:<a className="dash-button" href={d.sign_url} target="_blank" rel="noreferrer">Review & sign ↗</a>}{isOwner&&<button className="delete-action" onClick={()=>askDelete('document',d.id,d.title)}><Trash2 size={14}/>Delete</button>}</article>):<Vacant title="All clear for now">Assigned documents and completed copies will appear here.</Vacant>}</TabsContent>
<TabsContent value="messages"><div className="dash-section-header"><h2>Keep in touch</h2><div className="button-row">{isOwner&&<button className="dash-button secondary" disabled={!data.integrations.email} onClick={()=>open('email')}>Send email</button>}<button className="dash-button" disabled={!projects.length} onClick={()=>open('message')}>Project message</button></div></div>{owner&&!data.integrations.inbound&&<p className="setup-note">Incoming email is awaiting connection. Project messages work here; this is not a connected Gmail inbox.</p>}{data.messages.length?data.messages.map((m:R)=><article key={m.id} className="dash-panel"><div className="message-meta"><strong>{m.sender}</strong><span>{new Date(m.created_at).toLocaleString()} · {m.status}</span></div>{m.subject&&<h3>{m.subject}</h3>}<p className="message-body">{m.body}</p>{isOwner&&<button className="delete-action" onClick={()=>askDelete('message',m.id,m.subject||'Project message')}><Trash2 size={14}/>Delete message</button>}</article>):<Vacant title="Start the conversation">Share a note about a project. Messages stay with the assigned client.</Vacant>}</TabsContent>
<TabsContent value="settings"><div className="dash-section-header"><h2>Website & connections</h2><button className="dash-button" onClick={()=>open('settings')}>Edit website copy</button></div><div className="overview-grid"><div className="dash-panel"><h3>Connection checklist</h3><p>Secrets are configured securely by your developer. Never paste API keys into website content.</p>{Object.entries(data.integrations).map(([k,v])=><div className="connection-row" key={k}><span>{k}</span><span className="tag">{v?'Configured':'Awaiting setup'}</span></div>)}<a className="text-link" href="/setup-guide.txt" target="_blank" rel="noreferrer">View setup guide ↗</a></div><div className="dash-panel"><h3>Your public portfolio</h3><p>Enable “Publish to portfolio” only with the client’s permission. All media in that project becomes publicly visible.</p><p>Private galleries require account access. Download permissions control the download action; they cannot prevent screenshots.</p></div></div></TabsContent></Tabs>}
<Dialog open={!!modal} onOpenChange={v=>{if(!v&&!busy)setModal('')}}><DialogContent className={'dash-dialog '+(modal==='gallery'?'gallery-dialog':'')}><DialogTitle>{({client:'Add a client',project:editing?'Edit project':'Create a project',invoice:'Create an invoice',email:'Send client email',signature:'Request a signature',message:'Project message',settings:'Edit website copy',upload:'Add frames',gallery:selected?.title||'Gallery'} as R)[modal]||'Studio'}</DialogTitle><DialogDescription>{modal==='gallery'?selected?.description||'A little closer to the moments that matter.':modal==='upload'?'JPEG, PNG, WebP, MP4 or WebM. Up to 25 MB per file.':'Changes are saved securely to your studio.'}</DialogDescription>{notice&&<p className="dash-notice" role="status">{notice}</p>}
{modal==='gallery'?<><div className="gallery-toolbar"><span>{media.length} files · {media.filter((m:R)=>m.favorite).length} favourites</span>{isOwner?<button className="dash-button" onClick={()=>{setModal('upload');setFailed([])}}><Upload size={16}/>Add files</button>:<button className="dash-button" disabled={busy||!media.length} onClick={()=>perform({action:'submitSelections',id:projectId})}>{selected?.selections_submitted?'Selections submitted':'Submit selections'}</button>}</div>{media.length?<div className="gallery-grid">{media.map((m:R)=><div className="gallery-tile" key={m.id}><button className="gallery-open" onClick={()=>setLightbox(m)} aria-label={'Open '+m.name}>{m.type.startsWith('video/')?<video src={'/api/media/'+m.id} preload="metadata"/>:<img src={'/api/media/'+m.id} alt={m.name} loading="lazy"/>}</button><div className="media-actions"><span title={m.name}>{m.name}</span>{!isOwner?<button aria-label={m.favorite?'Remove favourite':'Save favourite'} aria-pressed={!!m.favorite} onClick={()=>perform({action:'favorite',id:m.id,selected:!m.favorite})}><Heart size={17} fill={m.favorite?'currentColor':'none'}/></button>:m.favorite?<span>♥</span>:null}{(isOwner||selected?.download_allowed===1)&&<a href={'/api/media/'+m.id+'?download=1'} aria-label={'Download '+m.name}><Download size={17}/></a>}</div>{isOwner&&<div className="media-edit"><label>Order<input type="number" min="0" max="10000" defaultValue={m.position} onBlur={e=>{if(Number(e.target.value)!==m.position)perform({action:'media',id:m.id,position:Number(e.target.value)})}}/></label>{m.type.startsWith('image/')&&<button onClick={()=>perform({action:'media',id:m.id,position:m.position,cover:true})}>{selected?.cover_id===m.id?'✓ Cover':'Set cover'}</button>}{isOwner&&<button className="delete-action" onClick={()=>askDelete('media',m.id,m.name)}><Trash2 size={14}/>Delete file</button>}</div>}</div>)}</div>:<Vacant title="A story is taking shape">{owner?'Upload the first photographs to this gallery.':'New photographs appear here when the studio adds them.'}</Vacant>}</>:modal==='upload'?<div><label className="upload-zone"><Upload/><strong>Choose files to add</strong><span>Files stay in this project.</span><input type="file" multiple disabled={busy} accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" onChange={e=>upload(Array.from(e.target.files||[]))}/></label>{progress!==null&&<><Progress value={progress}/><p>{Math.round(progress)}% uploaded</p></>}{failed.length>0&&<button className="dash-button" onClick={()=>upload(failed)}>Retry {failed.length} failed files</button>}</div>:<form className="dash-form" onSubmit={submit}>
{modal==='client'&&<><Field label="Client name" name="name" required/><Field label="Email address" name="email" type="email" required/><p className="fine">Share the Client Login link with this person. Their gallery will match this email when they sign in.</p></>}
{modal==='project'&&<><Field label="Project title" name="title" value={editing?.title} required/><Choice label="Client" value={clientId} change={setClientId} options={(data?.clients||[]).map((c:R)=>({value:c.id,label:c.name+' · '+c.email}))}/><Choice label="Service" value={service} change={setService} options={choice(['Photography','Videography','Live Streaming','Passport Photos'])}/><div className="dash-form-grid"><Field label="Session date" name="date" type="date" value={editing?.date}/><Choice label="Stage" value={stage} change={setStage} options={choice(['planning','scheduled','editing','delivered'])}/></div><label className="dash-field">Project description<textarea name="description" rows={3} defaultValue={editing?.description}/></label><label className="check-label"><Checkbox checked={download} onCheckedChange={v=>setDownload(v===true)}/>Allow client downloads</label><label className="check-label"><Checkbox checked={published} onCheckedChange={v=>setPublished(v===true)}/>Publish this project and all its media to the portfolio</label>{published&&<p className="setup-note">All project media becomes public. Confirm that you have the client’s permission.</p>}</>}
{['invoice','message','signature'].includes(modal)&&<Choice label="Project" value={projectId} change={setProjectId} options={projOptions}/>}
{modal==='invoice'&&<><Choice label="Currency" value={currency} change={setCurrency} options={['cad','usd','aud','gbp','eur','pkr'].map(x=>({value:x,label:x.toUpperCase()}))}/>{items.map((item,i)=><div className="invoice-item" key={i}>{(['description','quantity','amount'] as const).map(k=><label className="dash-field" key={k}>{k==='amount'?'Unit amount':k}<input required type={k==='description'?'text':'number'} min={k==='quantity'?1:.01} step={k==='quantity'?1:.01} value={item[k]} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,[k]:e.target.value}:x))}/></label>)}</div>)}<button className="text-link" type="button" onClick={()=>setItems([...items,{description:'',quantity:'1',amount:''}])}>+ Add line item</button><div className="dash-form-grid"><Field label="Tax percentage" name="tax" type="number" value="0"/><Field label="Deposit amount" name="deposit" type="number" value="0"/><Field label="Due date" name="due" type="date"/></div></>}
{modal==='email'&&<><Choice label="Client" value={clientId} change={setClientId} options={(data?.clients||[]).map((c:R)=>({value:c.id,label:c.name}))}/><Field label="Subject" name="subject" required/><label className="dash-field">Message<textarea name="body" rows={6} required/></label></>}
{modal==='signature'&&<><Field label="Document title" name="title" required/><Field label="Prepared DocuSeal template ID" name="templateId" type="number" required/><Field label="Signer role from DocuSeal template" name="signerRole" value="First Party" required/><p className="fine">The signer role must exactly match the template role in DocuSeal, for example First Party, Client, or Signer.</p></>}
{modal==='message'&&<label className="dash-field">Your message<textarea name="body" rows={6} required maxLength={4000}/></label>}
{modal==='settings'&&[{key:'studioStatement',label:'Studio statement'},{key:'aboutText',label:'About the studio'},{key:'contactEmail',label:'Contact email'},{key:'contactPhone',label:'Contact phone'},{key:'instagram',label:'Instagram HTTPS URL'},{key:'facebook',label:'Facebook HTTPS URL'},{key:'videoUrl',label:'Showreel HTTPS video URL'}].map(s=><Field key={s.key} name={s.key} label={s.label} value={data?.settings.find((v:R)=>v.key===s.key)?.value||({contactEmail:'supersnapstudio@gmail.com',contactPhone:'647-720-0423'} as R)[s.key]||''}/>)}
<button className="dash-button" disabled={busy||(['project','invoice','signature','message'].includes(modal)&&!(modal==='project'?clientId:projectId))}>{busy?'Saving…':modal==='email'?'Send email':modal==='signature'?'Send signature request':'Save'}<Check size={16}/></button></form>}</DialogContent></Dialog>
<Dialog open={!!deleting} onOpenChange={v=>{if(!v&&!busy){setDeleting(null);setNotice('')}}}><DialogContent className="dash-dialog"><DialogTitle>Delete {deleting?.label}?</DialogTitle><DialogDescription>This permanently removes the item from the website. Delete linked records first if prompted. Deleting an agreement or email here does not delete it from DocuSeal or the recipient’s inbox. Type DELETE to continue.</DialogDescription><label className="dash-field">Confirmation<input autoComplete="off" value={deleteText} onChange={e=>setDeleteText(e.target.value)} placeholder="DELETE"/></label>{notice&&<p className="dash-notice" role="alert">{notice}</p>}<div className="button-row"><button className="dash-button secondary" disabled={busy} onClick={()=>{setDeleting(null);setNotice('')}}>Cancel</button><button className="dash-button danger" disabled={busy||deleteText!=='DELETE'} onClick={confirmDelete}>{busy?'Deleting…':'Delete permanently'}</button></div></DialogContent></Dialog>
<Dialog open={!!lightbox} onOpenChange={v=>{if(!v)setLightbox(null)}}><DialogContent className="lightbox"><DialogTitle>{lightbox?.name}</DialogTitle><DialogDescription>Gallery preview</DialogDescription>{lightbox&&(lightbox.type.startsWith('video/')?<video src={'/api/media/'+lightbox.id} controls/>:<img src={'/api/media/'+lightbox.id} alt={lightbox.name}/>)}<div className="lightbox-nav"><button onClick={()=>setLightbox(media[(media.findIndex((m:R)=>m.id===lightbox?.id)-1+media.length)%media.length])}>← Previous</button><button onClick={()=>setLightbox(media[(media.findIndex((m:R)=>m.id===lightbox?.id)+1)%media.length])}>Next →</button></div></DialogContent></Dialog></main></div>}
