import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
import { PGlite } from '@electric-sql/pglite';
const load = async path => import('data:text/javascript;base64,' + Buffer.from(ts.transpileModule(readFileSync(path, 'utf8'), { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText).toString('base64'));
const { ownerEmailMatches, safeNext } = await load('lib/auth-rules.ts');
assert.equal(ownerEmailMatches('owner@example.com', undefined), false);
assert.equal(ownerEmailMatches('OWNER@example.com', 'owner@example.com'), true);
assert.equal(ownerEmailMatches('client@example.com', 'owner@example.com'), false);
for (const unsafe of ['https://evil.test', '//evil.test', '/\\evil.test', {}, null]) assert.equal(safeNext(unsafe), '/client');
assert.equal(safeNext('/admin?tab=projects'), '/admin?tab=projects');
const { checkoutAmount, verifiedPayment } = await load('lib/square-core.ts');
assert.equal(checkoutAmount({ total: 10000, paid: 0, deposit: 3000 }, true), 3000);
assert.equal(checkoutAmount({ total: 10000, paid: 3000, deposit: 3000 }, true), 7000);
assert.throws(() => checkoutAmount({ total: 10000, paid: 10000, deposit: 3000 }, false));
const attempt = { id: 'attempt1', order_id: 'order1', currency: 'cad', amount: 3000 };
const order = { id: 'order1', reference_id: 'attempt1', location_id: 'loc1', total_money: { amount: 3000, currency: 'CAD' } };
const payment = { id: 'payment1', order_id: 'order1', location_id: 'loc1', amount_money: { amount: 3000, currency: 'CAD' }, status: 'COMPLETED' };
assert.equal(verifiedPayment(payment, attempt, order, 'loc1').completed, true);
for (const bad of [{ ...payment, location_id: 'other' }, { ...payment, amount_money: { amount: 1, currency: 'CAD' } }, { ...payment, tip_money: { amount: 10 } }, { ...payment, refunded_money: { amount: 3001, currency: 'CAD' } }]) assert.throws(() => verifiedPayment(bad, attempt, order, 'loc1'));
const { validMediaHeader } = await load('lib/media-rules.ts');
assert.equal(validMediaHeader('image/jpeg', new Uint8Array([255,216,255,224])), true);
assert.equal(validMediaHeader('image/jpeg', new TextEncoder().encode('<script>')), false);
assert.equal(validMediaHeader('image/svg+xml', new TextEncoder().encode('<svg>')), false);

const pg = new PGlite();
await pg.exec(`create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create table auth.users(id uuid primary key);
create schema storage; create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
grant usage on schema public to anon,authenticated,service_role;`);
const schema = readFileSync('supabase/setup.sql', 'utf8');
assert.equal(schema, readFileSync('supabase/migrations/20260928140819_initial_studio.sql', 'utf8'));
await pg.exec(schema);
const scalar = async sql => Object.values((await pg.query(sql)).rows[0])[0];
assert.equal(await scalar("select count(*)::int from pg_tables where schemaname='public' and rowsecurity"), 15);
assert.equal(await scalar("select public from storage.buckets where id='studio-media'"), false);
for (const role of ['anon','authenticated']) {
  await pg.exec(`set role ${role}`);
  await assert.rejects(pg.query('select * from public.clients'), /permission denied/);
  await assert.rejects(pg.query("select public.studio_acquire_checkout('i1','x',1,2)"), /permission denied/);
  await pg.exec('reset role');
}
await pg.exec(`insert into auth.users values('00000000-0000-0000-0000-000000000001'); set role service_role;
insert into clients(id,email,name,created_at) values('c1','a@example.com','A',1),('c2','b@example.com','B',1);
insert into projects(id,client_id,title,service,created_at) values('p1','c1','Test','Photography',1);
insert into media(id,project_id,key,name,type,size,created_at) values('m1','p1','p1/m1','photo.jpg','image/jpeg',100,1);
insert into invoices(id,number,project_id,client_id,items,currency,subtotal,total,deposit,created_at) values('i1','SS-1','p1','c1','[]','cad',10000,10000,3000,1);`);
assert.equal(await scalar("select studio_rate_limit('ip',2,3600000)"), true);
assert.equal(await scalar("select studio_rate_limit('ip',2,3600000)"), true);
assert.equal(await scalar("select studio_rate_limit('ip',2,3600000)"), false);
await assert.rejects(pg.query("select studio_favorite('c2','m1',true)"), /Media not found/);
await pg.exec("select studio_favorite('c1','m1',true); select studio_favorite('c1','m1',true)");
assert.equal(await scalar('select count(*)::int from favorites'), 1);
await pg.exec("update projects set selections_submitted=1; select studio_favorite('c1','m1',false)");
assert.equal(await scalar('select selections_submitted from projects'), 0);
assert.equal(await scalar("select studio_acquire_checkout('i1','lock1',100,200)"), true);
assert.equal(await scalar("select studio_acquire_checkout('i1','lock2',101,201)"), false);
assert.equal(await scalar("select studio_acquire_checkout('i1','lock2',201,301)"), true);
await pg.exec(`insert into square_checkouts(id,invoice_id,amount,currency,paid_before,request_json,order_id,created_at) values('a1','i1',3000,'cad',0,'{}','o1',1);
select studio_record_square_payment('a1','pay1','o1',0);
select studio_record_square_payment('a1','pay1','o1',0);
select studio_record_square_payment('a1','pay1','o1',1000);
select studio_record_square_payment('a1','pay1','o1',0);`);
assert.equal(await scalar('select count(*)::int from payments'), 1);
assert.equal(Number(await scalar('select amount-refunded from payments')), 2000);
await assert.rejects(pg.query("select studio_record_square_payment('a1','pay1','wrong-order',0)"), /Invalid payment/);
await assert.rejects(pg.query("select studio_record_square_payment('a1','pay1','o1',4000)"), /Invalid payment/);
await pg.exec(`insert into uploads_pending(id,project_id,key,name,type,size,actor,created_at) values('u1','p1','p1/u1','test.jpg','image/jpeg',100,'00000000-0000-0000-0000-000000000001',1);`);
await assert.rejects(pg.query("select studio_finish_upload('u1','00000000-0000-0000-0000-000000000002')"), /Upload not found/);
await pg.exec("select studio_finish_upload('u1','00000000-0000-0000-0000-000000000001')");
assert.equal(await scalar("select count(*)::int from media where id='u1'"), 1);
assert.equal(await scalar('select count(*)::int from uploads_pending'), 0);
await pg.close();
console.log('PASS: schema, RLS/privileges, ownership, rate limits, checkout lock, payment replay/refunds, upload finalization, redirects and file validation.');
