import {env} from 'cloudflare:workers';import {getChatGPTUser} from '@/app/chatgpt-auth';
export type Row=Record<string,any>;export function config(){return env as unknown as Record<string,string|undefined>}
export class HttpError extends Error{constructor(message:string,public status=400){super(message)}}
export function db(){if(!env.DB)throw new HttpError('The studio is temporarily unavailable. Please try again.',503);return env.DB}
export function bucket(){if(!env.BUCKET)throw new HttpError('Media storage is temporarily unavailable.',503);return env.BUCKET}
export const uid=()=>crypto.randomUUID(),now=()=>Date.now();export async function all(sql:string,...p:any[]){return(await db().prepare(sql).bind(...p).all<Row>()).results}export async function one(sql:string,...p:any[]){return db().prepare(sql).bind(...p).first<Row>()}export async function run(sql:string,...p:any[]){return db().prepare(sql).bind(...p).run()}
export function isOwner(email:string){return email.toLowerCase()===(config().OWNER_EMAIL||'zameerpanhwer67@gmail.com').toLowerCase()}
export async function identity(ownerOnly=false){const user=await getChatGPTUser();if(!user)throw new HttpError('Please sign in to continue.',401);const owner=isOwner(user.email);if(ownerOnly&&!owner)throw new HttpError('Studio owner access required.',403);let client:Row|null=null;if(!owner){client=await one('SELECT * FROM clients WHERE user_id=?',user.userId);if(!client){const c=await one('SELECT * FROM clients WHERE email=? AND user_id IS NULL',user.email.toLowerCase());if(c){await run('UPDATE clients SET user_id=? WHERE id=? AND user_id IS NULL',user.userId,c.id);client=await one('SELECT * FROM clients WHERE user_id=?',user.userId)}}}return{user,owner,client}}
export async function projectAccess(id:string){const w=await identity(),p=await one('SELECT * FROM projects WHERE id=?',id);if(!p||!w.owner&&p.client_id!==w.client?.id)throw new HttpError('Project not found.',404);return{...w,project:p}}
export async function invoiceAccess(id:string){const w=await identity(),i=await one('SELECT i.*,c.name AS client_name,c.email AS client_email,COALESCE((SELECT SUM(amount-refunded) FROM payments p WHERE p.invoice_id=i.id),0) AS paid FROM invoices i JOIN clients c ON c.id=i.client_id WHERE i.id=?',id);if(!i||!w.owner&&i.client_id!==w.client?.id)throw new HttpError('Invoice not found.',404);return{...w,invoice:i}}
export function sameOrigin(req:Request){if(req.headers.get('origin')!==new URL(req.url).origin)throw new HttpError('Request origin is not allowed.',403)}
export async function body(req:Request){const text=await req.text();if(text.length>25000)throw new HttpError('Request is too large.',413);try{return JSON.parse(text) as Row}catch{throw new HttpError('Invalid request.')}}
export function str(v:unknown,max=4000,required=true){if(typeof v!=='string'||v.trim().length>max||required&&!v.trim())throw new HttpError('Please check the required fields.');return v.trim()}
export function email(v:unknown){const s=str(v,254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s))throw new HttpError('Please enter a valid email address.');return s}
export function integer(v:unknown,min=0,max=100000000){const n=Number(v);if(!Number.isSafeInteger(n)||n<min||n>max)throw new HttpError('Please enter a valid amount.');return n}
export async function log(actor:string,action:string,resource:string){await run('INSERT INTO audit VALUES (?,?,?,?,?)',uid(),actor,action,resource,now())}
export function json(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}})}
export function failure(e:unknown){if(e instanceof HttpError)return json({error:e.message},e.status);console.error('Studio request failed',e instanceof Error?e.message:'Unknown error');return json({error:'Unable to complete this request. Please try again.'},503)}
export function integrations(){const e=config();return{payments:!!(e.SQUARE_ACCESS_TOKEN&&e.SQUARE_LOCATION_ID&&e.SQUARE_WEBHOOK_SIGNATURE_KEY&&e.SQUARE_WEBHOOK_URL&&e.SITE_URL&&['sandbox','production'].includes(e.SQUARE_ENVIRONMENT||'')),email:!!(e.RESEND_API_KEY&&e.EMAIL_FROM),inbound:!!(e.RESEND_API_KEY&&e.RESEND_WEBHOOK_SECRET),signatures:!!(e.DOCUSEAL_API_KEY&&e.DOCUSEAL_WEBHOOK_SECRET)}}
