import {sqliteTable,text,integer,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const clients=sqliteTable('clients',{id:text('id').primaryKey(),email:text('email').notNull(),name:text('name').notNull(),userId:text('user_id'),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('clients_email').on(t.email),uniqueIndex('clients_user').on(t.userId)]);
export const enquiries=sqliteTable('enquiries',{id:text('id').primaryKey(),name:text('name').notNull(),email:text('email').notNull(),phone:text('phone'),service:text('service').notNull(),date:text('date'),location:text('location'),details:text('details').notNull(),status:text('status').notNull().default('new'),ipHash:text('ip_hash'),createdAt:integer('created_at').notNull()},t=>[index('enquiries_spam').on(t.ipHash,t.createdAt)]);
export const projects=sqliteTable('projects',{id:text('id').primaryKey(),clientId:text('client_id').notNull().references(()=>clients.id),title:text('title').notNull(),description:text('description').notNull().default(''),service:text('service').notNull(),date:text('date'),status:text('status').notNull().default('planning'),downloadAllowed:integer('download_allowed').notNull().default(0),published:integer('published').notNull().default(0),selectionsSubmitted:integer('selections_submitted').notNull().default(0),coverId:text('cover_id'),createdAt:integer('created_at').notNull()},t=>[index('projects_client').on(t.clientId)]);
export const media=sqliteTable('media',{id:text('id').primaryKey(),projectId:text('project_id').notNull().references(()=>projects.id),key:text('key').notNull(),name:text('name').notNull(),type:text('type').notNull(),size:integer('size').notNull(),position:integer('position').notNull().default(0),createdAt:integer('created_at').notNull()},t=>[index('media_project').on(t.projectId,t.position)]);
export const favorites=sqliteTable('favorites',{id:text('id').primaryKey(),clientId:text('client_id').notNull().references(()=>clients.id),mediaId:text('media_id').notNull().references(()=>media.id)},t=>[uniqueIndex('favorites_client_media').on(t.clientId,t.mediaId)]);
export const invoices=sqliteTable('invoices',{id:text('id').primaryKey(),number:text('number').notNull(),projectId:text('project_id').notNull().references(()=>projects.id),clientId:text('client_id').notNull().references(()=>clients.id),items:text('items').notNull(),currency:text('currency').notNull(),subtotal:integer('subtotal').notNull(),taxBps:integer('tax_bps').notNull().default(0),total:integer('total').notNull(),deposit:integer('deposit').notNull().default(0),due:text('due'),checkoutId:text('checkout_id'),checkoutUrl:text('checkout_url'),checkoutAmount:integer('checkout_amount'),checkoutExpires:integer('checkout_expires'),checkoutLock:text('checkout_lock'),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('invoice_number').on(t.number),index('invoices_client').on(t.clientId)]);
export const payments=sqliteTable('payments',{id:text('id').primaryKey(),invoiceId:text('invoice_id').notNull().references(()=>invoices.id),providerId:text('provider_id').notNull(),amount:integer('amount').notNull(),currency:text('currency').notNull(),refunded:integer('refunded').notNull().default(0),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('payments_provider').on(t.providerId),index('payments_invoice').on(t.invoiceId)]);
export const documents=sqliteTable('documents',{id:text('id').primaryKey(),projectId:text('project_id').notNull().references(()=>projects.id),clientId:text('client_id').notNull().references(()=>clients.id),title:text('title').notNull(),providerId:text('provider_id').notNull(),signUrl:text('sign_url'),status:text('status').notNull().default('sent'),completedUrl:text('completed_url'),auditUrl:text('audit_url'),createdAt:integer('created_at').notNull()},t=>[index('documents_client').on(t.clientId),uniqueIndex('documents_provider').on(t.providerId)]);
export const messages=sqliteTable('messages',{id:text('id').primaryKey(),projectId:text('project_id').references(()=>projects.id),clientId:text('client_id').references(()=>clients.id),sender:text('sender').notNull(),subject:text('subject'),body:text('body').notNull(),status:text('status').notNull().default('received'),providerId:text('provider_id'),createdAt:integer('created_at').notNull()},t=>[index('messages_client').on(t.clientId),uniqueIndex('messages_provider').on(t.providerId)]);
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const events=sqliteTable('events',{id:text('id').primaryKey(),provider:text('provider').notNull(),createdAt:integer('created_at').notNull()});
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),resource:text('resource').notNull(),createdAt:integer('created_at').notNull()});

export const squareCheckouts=sqliteTable('square_checkouts',{id:text('id').primaryKey(),invoiceId:text('invoice_id').notNull().references(()=>invoices.id),amount:integer('amount').notNull(),currency:text('currency').notNull(),paidBefore:integer('paid_before').notNull(),requestJson:text('request_json').notNull(),linkId:text('link_id'),orderId:text('order_id'),url:text('url'),status:text('status').notNull().default('creating'),createdAt:integer('created_at').notNull()},t=>[index('square_checkouts_invoice').on(t.invoiceId,t.status),uniqueIndex('square_checkouts_order').on(t.orderId),uniqueIndex('square_checkouts_link').on(t.linkId)]);
