import {squareSignature} from '@/lib/square-core';
import {squareConfig,reconcileSquarePayment} from '@/lib/square';
import {config,db,failure,HttpError,json,now,one,run,uid} from '@/lib/studio-server';import {equal,hmac} from '@/lib/providers';
export async function POST(req:Request,{params}:{params:Promise<{provider:string}>}){try{const{provider}=await params,e=config(),raw=await req.text();if(raw.length>1000000)throw new HttpError('Payload too large.',413);
if(provider==='square'){
  const c=squareConfig();
  if(!equal(req.headers.get('x-square-hmacsha256-signature')||'',await squareSignature(c.secret,c.webhook,raw)))throw new HttpError('Invalid Square signature.',403);
  const event=JSON.parse(raw);
  if(typeof event.event_id!=='string'||!event.event_id)throw new HttpError('Missing event ID.');
  const eventId='square:'+event.event_id;
  if(await one('SELECT id FROM events WHERE id=?',eventId))return json({ok:true});
  if(['payment.created','payment.updated','refund.created','refund.updated'].includes(event.type)){
    const paymentId=event.type.startsWith('refund.')?event.data?.object?.refund?.payment_id:event.data?.object?.payment?.id;
    if(typeof paymentId!=='string'||!paymentId)throw new HttpError('Missing payment ID.');
    await reconcileSquarePayment(paymentId);
  }
  await run('INSERT OR IGNORE INTO events VALUES (?,?,?)',eventId,'square',now());
  return json({ok:true});
}
if(provider==='docuseal'){if(!e.DOCUSEAL_WEBHOOK_SECRET||!e.DOCUSEAL_API_KEY)throw new HttpError('Webhook is not configured.',503);const[t,sig]=(req.headers.get('x-docuseal-signature')||'').split('.');if(!t||!sig||Math.abs(Date.now()/1000-Number(t))>300||!equal(sig,await hmac(e.DOCUSEAL_WEBHOOK_SECRET,t+'.'+raw)))throw new HttpError('Invalid signature.');const event=JSON.parse(raw),id=String(event.data?.submission_id||event.data?.id||''),doc=await one('SELECT * FROM documents WHERE provider_id=?',id);if(!doc)return json({ok:true});const r=await fetch('https://api.docuseal.com/submissions/'+encodeURIComponent(id),{headers:{'X-Auth-Token':e.DOCUSEAL_API_KEY}});if(!r.ok)throw new HttpError('Provider unavailable.',502);const s:any=await r.json(),status=s.status||(s.completed_at?'completed':'sent'),safe=(v:unknown)=>typeof v==='string'&&v.startsWith('https://')?v:null;await run('UPDATE documents SET status=?,completed_url=?,audit_url=? WHERE id=?',status,status==='completed'?safe(s.combined_document_url||s.submitters?.[0]?.documents?.[0]?.url):null,status==='completed'?safe(s.audit_log_url):null,doc.id);return json({ok:true})}
if(provider==='resend'){if(!e.RESEND_WEBHOOK_SECRET||!e.RESEND_API_KEY)throw new HttpError('Webhook is not configured.',503);const id=req.headers.get('svix-id')||'',t=req.headers.get('svix-timestamp')||'',sigs=req.headers.get('svix-signature')||'';if(!id||!t||Math.abs(Date.now()/1000-Number(t))>300)throw new HttpError('Invalid signature.');const key=await crypto.subtle.importKey('raw',Uint8Array.from(atob(e.RESEND_WEBHOOK_SECRET.replace(/^whsec_/,'')),c=>c.charCodeAt(0)),{name:'HMAC',hash:'SHA-256'},false,['sign']);const bytes=new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(id+'.'+t+'.'+raw))),expected=btoa(String.fromCharCode(...bytes));if(!sigs.split(' ').some(s=>equal(s.replace(/^v1,/,''),expected)))throw new HttpError('Invalid signature.');if(await one('SELECT id FROM events WHERE id=?',id))return json({ok:true});const event=JSON.parse(raw);if(event.type==='email.received'){const r=await fetch('https://api.resend.com/emails/receiving/'+encodeURIComponent(event.data.email_id),{headers:{Authorization:'Bearer '+e.RESEND_API_KEY}});if(!r.ok)throw new HttpError('Email unavailable.',502);const m:any=await r.json(),from=String(m.from||event.data.from),sender=(from.match(/<([^>]+)>/)?.[1]||from).trim().toLowerCase(),client=await one('SELECT id FROM clients WHERE email=?',sender);await db().batch([db().prepare('INSERT OR IGNORE INTO messages (id,client_id,sender,subject,body,status,provider_id,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(uid(),client?.id||null,from,String(m.subject||'').slice(0,200),String(m.text||'No plain text body. Read this email in the provider inbox.').slice(0,20000),'received',event.data.email_id,now()),db().prepare('INSERT OR IGNORE INTO events VALUES (?,?,?)').bind(id,'resend',now())])}else await db().batch([db().prepare('UPDATE messages SET status=? WHERE provider_id=?').bind(String(event.type).replace('email.',''),String(event.data?.email_id||'')),db().prepare('INSERT OR IGNORE INTO events VALUES (?,?,?)').bind(id,'resend',now())]);return json({ok:true})}throw new HttpError('Webhook not found.',404)}catch(e){return failure(e)}}
